### ISSUE TITLE
Ошибка на сайте http://allframeworks.ru/codeception/11-Codecoverage.html

### ISSUE THREAD

**Issue by Jagepard** [yupe/codeception-guide-ru#28]
**Удаленное покрытие тестами**
В случае, **_есои_** ваше приложение запущено с помощью веб-сервера (Apache, Nginx, PHP WebServer) у вас нет доступа к тестируемому коду,
таким образом сбор данных о покрытии кода становится нетривиальной задачей. То же самое **_каается_** скриптов запущенных на другом узле.

P.S. В файле 11-Codecoverage.md этих опечаток нет

**Comment by DexterHD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Тестовая карточка](https://trello.com/c/pkqRcsly/1-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%B0%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B0)

**Comment by yupe** [comment]
@DexterHD что за карточка?

**Comment by DexterHD** [comment]
@yupe Упс, соррян. Это я проверял Трелло... Удаляю ))
